dose:
  name: Dose
  description: Dose a specified amount on the matching Dosing Controller entry.
  fields:
    pump:
      description: Name of the Dosing Controller entry (optional; if omitted this entry will run).
      example: "Reef Pump A"
    ml:
      description: Amount to dose in milliliters.
      example: 2.5
      required: true
      selector:
        number:
          min: 0
          max: 999
          step: 0.1
