esphome:
  name: dosing-controller
  friendly_name: "Dosing Controller"

esp32:
  board: esp32dev

wifi:
  ssid: YOUR_SSID
  password: YOUR_PASSWORDs
  ap:
    ssid: "Dosing Pump Setup"
    password: "pump1234"

logger:
api:

ota:
  platform: esphome

captive_portal:

web_server:
  port: 80
  
time:
  - platform: sntp
    id: sntp_time

external_components:
  - source:
      type: local
      path: components
    components: [doser, doser_scheduler]

packages:
  pump1: !include
    file: packages/pump.yaml
    vars:
      pump_id: pump1
      pump_name: "Pump 1"
      step_pin: GPIO26
      dir_pin: GPIO27
      dir_inverted: true
      sleep_pin: GPIO25
      sleep_inverted: true
  pump2: !include
    file: packages/pump.yaml
    vars:
      pump_id: pump2
      pump_name: "Pump 2"
      step_pin: GPIO19
      dir_pin: GPIO21
      dir_inverted: true
      sleep_pin: GPIO18
      sleep_inverted: true
  schedule1: !include
    file: packages/schedule.yaml
    vars:
      pump_id: pump1
      pump_name: "Pump 1"
  schedule2: !include
    file: packages/schedule.yaml
    vars:
      pump_id: pump2
      pump_name: "Pump 2"
