esphome:
  name: dosing-controller
  friendly_name: "Dosing Controller"

esp32:
  board: esp32dev

wifi:
  ssid: YOUR_SSID
  password: YOUR_PASSWORD
  ap:
    ssid: "Dosing Pump Setup"
    password: "dosingpump"

logger:
api:

ota:
  platform: esphome

web_server:
  port: 80

captive_portal:
  
external_components:
  - source:
      type: local
      path: components
    components: [doser]
